apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-connector-ams-mifos
  labels:
    app: ph-ee-connector-ams-mifos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-connector-ams-mifos
  template:
    metadata:
      labels:
        app: ph-ee-connector-ams-mifos
    spec:
      containers:
        - name: ph-ee-connector-ams-mifos
          image: "lalithkota/ph-ee-connector-ams-mifos:v1.0.0"
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512M"
              cpu: "500m"
            requests:
              memory: "512M"
              cpu: "100m"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "fin12,bb"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
