dependencies:
- name: zeebe-cluster-helm
  repository: https://helm.camunda.io
  version: 1.0.0
  condition: "zeebe-cluster-helm.enabled"
- name: zeebe-operate-helm
  repository: https://helm.camunda.io
  version: 1.2.0
  condition: "zeebe-operate-helm.enabled"
- name: elasticsearch
  repository: http://helm.elastic.co
  version: 7.16.3
  condition: "elasticsearch.enabled"
- name: kibana
  repository: http://helm.elastic.co
  version: 7.16.3
  condition: "kibana.enabled"
- name: mysql
  version: 8.8.23
  repository: "https://charts.bitnami.com/bitnami"
  alias: operationsmysql
  condition: "operations.mysql.enabled"
- name: kafka
  repository: https://charts.bitnami.com/bitnami
  version: 20.0.0
  condition: "kafka.enabled"
