zeebe:
    broker:
      contactpoint: "zeebe-zeebe-gateway:26500"

zeebe-cluster-helm:
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "ph-ee-elasticsearch"

  image:
    repository: camunda/zeebe
    tag: 1.1.0

  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  cpuThreadCount: "2"
  ioThreadCount: "2"
  pvcSize: "10Gi"
  pvcAccessModes: [ "ReadWriteOnce" ]

  resources:
    requests:
      cpu: 100m

  env:
#    - name: ZEEBE_BROKER_BACKPRESSURE_ENABLED
#      value: "false"
    - name: ZEEBE_BROKER_EXECUTION_METRICS_EXPORTER_ENABLED
      value: "true"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME
      value: "hu.dpc.rt.kafkastreamer.exporter.NoOpExporter"
    - name: ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_JARPATH
      value: "/exporters/ph-ee-kafka-exporter.jar"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_CLASSNAME
      value: "hu.dpc.rt.kafkastreamer.exporter.KafkaExporter"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_INITIALLIMIT
      value: "1000"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_ALPHA
      value: "2"
    - name: ZEEBE_BROKER_BACKPRESSURE_VEGAS_BETA
      value: "8"
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_EVENT
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_VARIABLE
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_PROCESSINSTANCE
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_PROCESS
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_INCIDENT
      value: 'true'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_DEPLOYMENT
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_ERROR
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_JOB
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_VARIABLEDOCUMENT
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_WORKFLOWINSTANCE
      value: 'false'
    - name: ZEEBE_BROKER_EXPORTERS_KAFKA_ARGS_INDEX_CREATETEMPLATE
      value: 'false'


  gateway:
    replicas: 1
    logLevel: warn
    env:
      - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
        value: "4"
      - name: ZEEBE_GATEWAY_MONITORING_ENABLED
        value: "true"

  # zeebe's dependencies
  elasticsearch:
    enabled: false
    fullnameOverride: "zeebe-elasticsearch"
    clusterName: "zeebe-elasticsearch"

  kibana:
    enabled: false
    fullnameOverride: "zeebee-kibana"
    elasticsearchHosts: "http://zeebe-elasticsearch:9200/"

  prometheus:
    enabled: false

  extraInitContainers: |
    - name: init-ph-ee-kafka-exporter
      image: busybox:1.28
      command: ['/bin/sh', '-c']
      args: ['wget -O /exporters/ph-ee-kafka-exporter.jar "https://fynarfin.io/images/exporter-1.1.0-SNAPSHOT.jar"; ls -al /exporters/']
      volumeMounts:
      - name: exporters
        mountPath: /exporters/

# payment hub Operate, ES and Kibana
zeebe-operate-helm:
  enabled: true
  image:
    repository: camunda/operate
    tag: 1.1.0
  fullnameOverride: "zeebe-operate"
  global:
    zeebe: "zeebe-zeebe"
    elasticsearch:
      host: "ph-ee-elasticsearch"
      clusterName: "ph-ee-elasticsearch"

elasticsearch:
  enabled: true
  imageTag: 7.16.3
  replicas: 1
  fullnameOverride: "ph-ee-elasticsearch"
  clusterName: "ph-ee-elasticsearch"
  minimumMasterNodes: 1
  esConfig:
    elasticsearch.yml: |
      xpack.security.enabled: false
      xpack.security.transport.ssl.enabled: false
      xpack.security.http.ssl.enabled: false
  secretMounts: []
  extraEnvs: []


kibana:
  enabled: true
  imageTag: 7.16.3
  fullnameOverride: "ph-ee-kibana"
  elasticsearchHosts: "http://ph-ee-elasticsearch:9200/"
  protocol: http
  kibanaConfig:
    kibana.yml: |
      monitoring.enabled: false
      xpack.security.enabled: false
      server.ssl.enabled: false
  secretMounts: []
  extraEnvs: []

channel:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-connector-channel"
  imageTag: "v1.1.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "bb"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  TRANSACTION_ID_LENGTH: 20
  DFSPIDS: "tn03,tn04"
  hostname: "ph-channel-dev.openg2p.mosip.net"
  stub_hostname: "ph-channel-gsma-dev.openg2p.mosip.net"
  limits:
    memory: "768M"
    cpu: "500m"
  requests:
    memory: "768M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/channel"
    annotations: {}
    backend: {}
    stub_backend: {}
  deployment:
    annotations: {}

operations:
  enabled: true
  mysql:
    enabled: true

ingress:
  apiversion: "networking.k8s.io/v1"

deployment:
  apiversion: "apps/v1"

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

operationsmysql:
  fullnameOverride: "operationsmysql"
  image:
      tag: "5.7"
      debug: false
  auth:
      database: "tenants"
      username: "mifos"
      password: "password"
      rootPassword: "4ET6ywqlGt"
  initdbScripts:
    setup.sql: |-
      CREATE DATABASE messagegateway;
      CREATE DATABASE `tn03`;
      CREATE DATABASE `tn04`;
      GRANT ALL PRIVILEGES ON `tn03`.* TO 'mifos';
      GRANT ALL PRIVILEGES ON `tn04`.* TO 'mifos';
      GRANT ALL ON *.* TO 'root'@'%';
      GRANT ALL PRIVILEGES ON messagegateway.* TO 'mifos';

ph_ee_connector_ams_mifos:
  enabled: false
  replicas: 1
  image: "lalithkota/ph-ee-connector-ams-mifos"
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "fin12,bb"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

ph_ee_connector_mojaloop:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-connector-mojaloop-java"
  imageTag: "v1.0.0-gradle"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "bb"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

operations_app:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-operations-app"
  imageTag: "v1.0.6"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "bb"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  hostname: "ph-opsapp-dev.openg2p.mosip.net"
  tenants: "tn03,tn04"
  token_client_channel_secret: ""
  datasource:
      username: "mifos"
      password: "password"
      host: "operationsmysql"
      port: 3306
      schema: "tenants"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}


operations_web:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-operations-web"
  imageTag: "v1.2.0"
  imagePullPolicy: "Always"
  hostname: "ph-ops-dev.openg2p.mosip.net"
  webhost: "ph-ops-dev.openg2p.mosip.net"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

identity:
  hostname: "ph-opsapp-dev.openg2p.mosip.net"

mpesa:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.2.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  zeebe_init_transfer_wait_timer: 10
  tenant: ""
  callback_host: ""
  accounts:
    default:
      name: "default"
      business_short_code: "7385028"
      till: "1234567"
      auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
      api_host: "https://sandbox.safaricom.co.ke"
      client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
      client_secret: "YzuGNoJxeub8ZC6d"
      pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
    roster:
      name: "roster"
      business_short_code: "7385028"
      till: "1234567"
      auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
      api_host: "https://sandbox.safaricom.co.ke"
      client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
      client_secret: "YzuGNoJxeub8ZC6d"
      pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
    paygops:
      name: "paygops"
      business_short_code: "174379"
      till: "9347335"
      auth_host: "https://sandbox.safaricom.co.ke/oauth/v1/generate"
      api_host: "https://sandbox.safaricom.co.ke"
      client_key: "0pLxbN83FrOl5Nd0Fh9Zi5BQlMxSL2n5"
      client_secret: "YzuGNoJxeub8ZC6d"
      pass_key: "bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/mpesa"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

roster_connector:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.2"
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  SPRING_PROFILES_ACTIVE: ""
  containerPort: 5000
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ams:
    local:
      enabled: ""
  pesacore:
    auth_header: ""
  deployment:
    annotations: {}

paygops_connector:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.2.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  containerPort: 5000
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "256M"
    cpu: "50m"
  ams:
    local:
      enabled: ""
  paygops:
    authheader: ""
  deployment:
    annotations: {}

messagegateway:
  enabled: false
  replicas: 1
  image: "lalithkota/ph-ee-message-gateway"
  imageTag: "v1.0.0"
  secret:
    value:
      api_key: ""
      project_id: ""
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: "ph-messagegateway-dev.openg2p.mosip.net"
  CALLBACKCONFIG_HOST: "ph-ee-connector-notifications"
  HOSTCONFIG_HOST: "message-gateway"
  MYSQL_USERNAME: "mifos"
  MYSQL_PASSWORD: "password"
  DATASOURCE_URL: jdbc:mysql:thin://operationsmysql:3306/messagegateway
  PROVIDERSOURCE_FROMDATABASE: "disabled"
  PROVIDERSOURCE_FROMYML: "enabled"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

notifications:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-notifications"
  imageTag: "v1.0.1"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "bb"
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: "ph-notifications-dev.openg2p.mosip.net"
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  MESSAGEGATEWAYCONFIG_HOST: "message-gateway"
  NOTIFICATION_LOCAL_HOST: "ph-ee-connector-notifications"
  NOTIFICATION_SUCCESS_ENABLED: "false"
  NOTIFICATION_FAILURE_ENABLED: "false"
  hostconfig:
    host: "message-gateway"
    port: "80"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

zeebe_ops:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-zeebe-ops"
  imageTag: "v1.0.1"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "bb"
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: "ph-zeebeops-dev.openg2p.mosip.net"
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  elasticsearch_contactpoint: "ph-ee-elasticsearch:9200"
  elasticsearch_sslverification: false
  elasticsearch_security_enabled: false
  tenants: "tn03,tn04"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}

importer_es:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-importer-es"
  imageTag: "v1.2.1"
  imagePullPolicy: "Always"
  reporting:
    enabled: true
    fields:
      amount: true
      accountId: true
      errorCode: false
      errorDescription: true
      externalId: true
      initiator: false
      initiatorType: false
      isNotificationsFailureEnabled: false
      isNotificationsSuccessEnabled: false
      mpesaTransactionId: false
      mpesaTransactionStatusRetryCount: false
      originDate: false
      partyLookupFailed: false
      phoneNumber: true
      processDefinitionKey: false
      processInstanceKey: true
      scenario: false
      tenantId: false
      timer: false
      timestamp: true
      transactionFailed: false
      transactionId: false
      transferCreateFailed: false
      transferSettlementFailed: false
      transferResponseCREATE: false
  elasticsearch_sslverification: false
  elasticsearch_security_enabled: false
  logging:
    level:
      root: "INFO"
    pattern:
      console: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
    javaToolOptions: "-Xmx256M"

kafka:
  enabled: true
  fullnameOverride: "kafka"
  logRetentionBytes: _1073741824
  defaultReplicationFactor: 1
  offsetsTopicReplicationFactor: 1
  transactionStateLogReplicationFactor: 1
  replicaCount: 1
  autoCreateTopicsEnable: true
  deleteTopicEnable: true

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 3Gi

  zookeeper:
    fullnameOverride: "zookeeper"
    replicaCount: 1
    persistence:
      enabled: true
      size: 3Gi

  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

importer_rdbms:
  enabled: true
  replicas: 0
  image: "lalithkota/ph-ee-importer-rdbms"
  imageTag: "v1.0.8"
  imagePullPolicy: "Always"
  LOGGING_LEVEL_ROOT: "INFO"
  LOGGING_PATTERN_CONSOLE: "%d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n"
  datasource:
      username: "mifos"
      password: "password"
      host: "operationsmysql"
      port: 3306
      schema: "tenants"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}
  javaToolOptions: "-Xmx256M"

connector_bulk:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-bulk-processor"
  imageTag: "v1.2.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "bb"
  hostname: "ph-bulk-dev.openg2p.mosip.net"
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  tenants: "tn03,tn04"
  bucket_name: "paymenthub-ee-dev"
  operations_app:
      contactpoint: "https://ops-bk.sandbox.fynarfin.io/"
      endpoints:
        batch_transaction: "/api/v1/batch/transactions"
  config:
    partylookup:
      enable: false
    approval:
      enable: false
    ordering:
      enable: false
      field: ""
    splitting:
      enable: true
      sub_batch_size: 5
    formatting:
      enable: false
      standard: "DEFAULT"
    mergeback:
      enable: true
    backpressure:
      enable: false
    success_threshold_check:
      enable: true
      success_rate: 95
  aws:
    region: "us-east-2"
    access_key: 'a'
    secret_key: 'a'
  limits:
    memory: "990M"
    cpu: "512m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}
  ingress:
    enabled: false

ph_ee_connector_gsma:
  enabled: true
  replicas: 1
  image: "lalithkota/ph-ee-connector-gsma-mm"
  imageTag: "v1.0.0"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: "bb"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

ph_ee_connector_slcb:
  enabled: false
  replicas: 1
  image: ""
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  username: "username"
  password: "password"
  signature_key: "long_segnature_key"
  auth_host: "https://g2p-test.slcb.com:8443"
  api_host: "https://g2p-test.slcb.com:8443"
  account_number: "003001003879112168"
  account_type: 0
  institutioncode: "SLCB"
  endpoint:
    auth: "/api/auth"
    transaction_request: "/api/transactionRequest"
    reconciliation: "/reconciliation"
    account_balance: "/accountBalance"
  config:
    date_format: "yyyy-MM-dd'T'hh:mm:ssXXX"
    reconciliation:
      enable: false
  aws:
    bucket_name: "paymenthub-ee-dev"
    region: "us-east-2"
    access_key: "access-key"
    secret_key: "secret-key"
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  deployment:
    annotations: {}

wildcardhostname: ""

tls: ""
